### PR TITLE
[PPP-3862]-Use of vulnerable component spring-core 4.1.2 SONATYPE 2015-0003

### PR DESCRIPTION
**Pull request by stepanovdg**

### CODE REVIEW

**Comment by stepanovdg** [comment]
@mchen-len-son @rmansoor @mbatchelor Could you please take a look?

**Comment by mchen-len-son** [comment]
@stepanovdg can you please add a comment to the features xml on why we need those features copied and overriden.
thanks.

**Comment by stepanovdg** [comment]
@mchen-len-son  Updated.

**Comment by mchen-len-son** [comment]
@pamval please take a look

**Pull request merged**
