### PR TITLE
[BACKLOG-5216] - PMR libraries staging archive lacks some pentaho karaf features

### PR DESCRIPTION
**Pull request by mtseu**
Add missing features.
An attempt has been made to make it as close to kettle-client as it's possible:
only three features were skipped: dataservice, metaverse and marketplace
apparently they are not needed on pmr runtime

@dkincade @brosander

### CODE REVIEW

**Comment by mtseu** [comment]
six-dot-oh PR: https://github.com/pentaho/pentaho-karaf-assembly/pull/128

**Comment by brosander** [comment]
@mtseu 
It looks like it was removed by this commit:
https://github.com/pentaho/pentaho-karaf-assembly/commit/9e38c691f8feb668ad4dd93959ff890433188912#diff-0981a09607be703b087d5da5e6614cbcL185

I'd double check with Nick that this is the best approach, we shouldn't need all the pdi client stuff in there though.

**Comment by pentaho-nbaker** [comment]
Please submit a pull-request for 6.0.0.0

**Comment by brosander** [comment]
@pentaho-nbaker https://github.com/pentaho/pentaho-karaf-assembly/pull/128

**Pull request merged**
