### PR TITLE
[BACKLOG-5653] - pdi-data-refinery converted from legacy plugin to maven bundle and feature

### PR DESCRIPTION
**Pull request by rfellows**
[BACKLOG-5653] - pdi-data-refinery converted from legacy plugin to maven bundle and feature

### CODE REVIEW

**Comment by rfellows** [comment]
@lgrill-pentaho, @smaring, @bytekast please review

**Comment by lgrill-pentaho** [comment]
Good as far as i can tell. Not a critical requirement, but going forward I'm going to push for version propertization for all pentaho AND third party dependencies in all features xml files. This will allow us manage version control from the top level project pom (DRY).

**Comment by rfellows** [comment]
depends on https://github.com/pentaho/pentaho-data-refinery-ee/pull/541

please don't merge until that is complete.

**Comment by rfellows** [comment]
@lgrill-pentaho I updated to use the properties. good catch. i forgot to do this before.

**Pull request merged**
