### PR TITLE
[BACKLOG-6318] - Added common-ui as a dependency of pdi-marketplace feature

### PR DESCRIPTION
**Pull request by graimundo**

### CODE REVIEW

**Comment by graimundo** [comment]
@nantunes please review

**Comment by nantunes** [comment]
Trivial change, seems ok to me. @graimundo please do the merge.

**Comment by lucboudreau** [comment]
As trivial as it may seem, please check with the build team to make sure this won't break the build.

**Comment by graimundo** [comment]
@lucboudreau We checked that the zip artifact for common-ui is available in nexus (it is an already existing artifact) and tested locally the build of karaf-assembly. Should we test for anything further? Do you anticipate any issue with the commit?

**Comment by lucboudreau** [comment]
The usual issues are related to the build order. Having common-ui as a dependency means that the build team needs to schedule this project to be built before it. That's why it is important to notify them so that they can check their build order.

**Comment by graimundo** [comment]
@lucboudreau @nantunes [Reverted the commit](https://github.com/pentaho/pentaho-karaf-assembly/commit/8f84f06d478130558f974bb1e91f5ee1633c2805) and will reach out to the build team to make sure we don't have any build order issues.

**Pull request merged**
