### PR TITLE
[BACKLOG-33243] Adding configuration to whitelist the loop back addre…

### PR DESCRIPTION
**Pull request by ccaspanello**
…ss for thin dialogs so they cannot be accessed externally

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 10s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/client
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 37s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl assemblies/client
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by NJtwentyone** [comment]
looks good

**Comment by ccaspanello** [comment]
Backports:
9.0 - PR #626
9.0.0.0 - PR #627

**Pull request merged**
