### PR TITLE
[PPP-3448] Apache CXF 3.0.6 Vulnerability w/SAML

### PR DESCRIPTION
**Pull request by SergeyTravin**

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@pentaho-nbaker, 

It is update the Apache CXF to 3.0.7
could you review it, please?

**Comment by SergeyTravin** [comment]
@pentaho-nbaker, @brosander could you review it, please?

**Comment by pamval** [comment]
@pentaho-nbaker this should get in as soon as possible.
@rmansoor if you have spare cycles, please review as well.

**Comment by rmansoor** [comment]
@pamval validating it locally right now

**Comment by kurtwalker** [comment]
@SergeyTravin @pentaho-nbaker @rmansoor @brosander @pamval I believe this pull request broke the karaf-assembly-ee builds.  http://cerberus.pentaho.com/job/master-nightly/job/karaf-ee-assembly/
Is failing with error message, "Unable to find the feature 'cxf-core'"  Do we need a similar change in karaf-ee?

**Comment by pamval** [comment]
Yes, I think that we need the change in karaf-ee as well.

**Pull request merged**
